<?php

declare(strict_types=1);

namespace App\Models;

class ClientRenewalsXlsxExporter
{
    public static function build(
        ?array $client,
        ?array $project,
        array $stats,
        array $yearComparison,
        array $activeBatches,
        array $historyLogs,
        array $options = []
    ): string {
        $sheets = [];

        $includeSummary = !empty($options['include_summary']);
        $includeActive = !empty($options['include_active']);
        $includeHistory = !empty($options['include_history']);
        $includeNotes = !empty($options['include_notes']);
        $scheduleMode = $options['schedule_mode'] ?? 'contract';

        // Default to all if none selected
        if (!$includeSummary && !$includeActive && !$includeHistory) {
            $includeSummary = true;
            $includeActive = true;
            $includeHistory = true;
        }

        if ($includeSummary) {
            $sheets[] = [
                'name' => 'Executive Statement',
                'rows' => self::buildSummarySheetRows($client, $project, $stats, $yearComparison, $options),
                'boldRows' => [1, 2, 3, 4, 5, 6, 7, 9, 10, 15, 16],
                'numericColumns' => ['B', 'C'],
            ];
        }

        if ($includeActive) {
            $sheets[] = [
                'name' => $scheduleMode === 'platform' ? 'Platform Licences' : 'Active Licences',
                'rows' => self::buildActiveBatchesRows($activeBatches, $includeNotes, $scheduleMode),
                'boldRows' => [1],
                'numericColumns' => ['E', 'H'],
            ];
        }

        if ($includeHistory) {
            $sheets[] = [
                'name' => 'Renewal Audit Trail',
                'rows' => self::buildHistoryRows($historyLogs, $includeNotes, $scheduleMode),
                'boldRows' => [1],
                'numericColumns' => ['G'],
            ];
        }

        return self::zip(self::workbookFiles($sheets));
    }

    private static function buildSummarySheetRows(
        ?array $client,
        ?array $project,
        array $stats,
        array $yearComparison,
        array $options
    ): array {
        $rows = [];
        $isPlatform = (($options['schedule_mode'] ?? 'contract') === 'platform');
        $clientName = $client['name'] ?? 'All Clients';
        $projectName = $project['name'] ?? 'All Projects';
        $dateRange = (!empty($options['from_date']) || !empty($options['to_date']))
            ? ($options['from_date'] ?? 'Beginning') . ' to ' . ($options['to_date'] ?? 'Present')
            : 'All Time (Full Lifetime History)';

        $title = $isPlatform
            ? 'EduRiser PMS — Platform Licences Allocation Statement'
            : 'EduRiser PMS — Client Licences Statement & Audit';
        $scheduleTypeLabel = $isPlatform
            ? 'Platform Schedule (Operational Delivery)'
            : 'Contract Schedule (Official Client Term)';

        $rows[] = [$title];
        $rows[] = ['Schedule Type:', $scheduleTypeLabel];
        $rows[] = ['Client:', $clientName];
        $rows[] = ['Project:', $projectName];
        $rows[] = ['Period Covered:', $dateRange];
        $rows[] = ['Generated On:', date('d M Y, h:i A')];
        $rows[] = ['Generated By:', $options['exported_by'] ?? 'System User'];
        $rows[] = [];

        // KPI Summary Block
        $rows[] = ['=== EXECUTIVE LICENCE SUMMARY ==='];
        $rows[] = ['Metric', 'Value'];
        $rows[] = ['Current Active Licences', (int) ($stats['total_licences'] ?? 0)];
        $rows[] = ['Active Batches Count', (int) ($stats['active_count'] ?? 0)];
        $rows[] = ['Batches Expiring in 30 Days', (int) ($stats['expiring_30_days'] ?? 0)];
        $rows[] = ['Overdue / Expired Batches', (int) ($stats['overdue_count'] ?? 0)];
        $rows[] = [];

        // Year-by-Year Comparison Table
        $rows[] = ['=== YEAR-BY-YEAR LICENCE ALLOCATION COMPARISON ==='];
        $rows[] = ['Year', 'Licences Allocated / Active in Year', 'Batches Count', 'Cycle Status'];

        if (empty($yearComparison)) {
            $rows[] = ['No historical year records found', 0, 0, '-'];
        } else {
            foreach ($yearComparison as $year => $data) {
                $rows[] = [
                    (string) $year,
                    (int) ($data['licences'] ?? 0),
                    (int) ($data['batches'] ?? 0),
                    $data['status'] ?? 'Completed',
                ];
            }
        }

        return $rows;
    }

    private static function buildActiveBatchesRows(array $batches, bool $includeNotes, string $scheduleMode = 'contract'): array
    {
        $isPlatform = ($scheduleMode === 'platform');
        $startHeader = $isPlatform ? 'Platform Start Date' : 'Creation Date';
        $renewalHeader = $isPlatform ? 'Platform Renewal Date' : 'Renewal Date';

        $headers = [
            'Client',
            'Project',
            'Batch Name',
            'Region / Department',
            'Licence Count',
            $startHeader,
            $renewalHeader,
            'Days Remaining',
            'Urgency Status',
            'Given By',
        ];
        if ($includeNotes) {
            $headers[] = $isPlatform ? 'Platform Delivery Notes' : 'Contract Notes / PO Ref';
        }

        $rows = [$headers];

        foreach ($batches as $b) {
            if ($isPlatform) {
                $startDate = !empty($b['platform_start_date']) ? $b['platform_start_date'] : ($b['creation_date'] ?? null);
                $renewalDate = !empty($b['platform_renewal_date']) ? $b['platform_renewal_date'] : ($b['renewal_date'] ?? null);
            } else {
                $startDate = $b['creation_date'] ?? null;
                $renewalDate = $b['renewal_date'] ?? null;
            }

            $row = [
                $b['client_name'] ?? '-',
                $b['project_name'] ?? '-',
                $b['batch_name'] ?? '-',
                $b['region_department'] ?? '-',
                (int) ($b['licence_count'] ?? 0),
                !empty($startDate) ? date('d-m-Y', strtotime($startDate)) : '-',
                !empty($renewalDate) ? date('d-m-Y', strtotime($renewalDate)) : '-',
                (int) ($b['days_remaining'] ?? 0),
                $b['urgency_label'] ?? $b['urgency_status'] ?? 'Active',
                $b['given_by'] ?? '-',
            ];
            if ($includeNotes) {
                $row[] = $b['notes'] ?? '-';
            }
            $rows[] = $row;
        }

        return $rows;
    }

    private static function buildHistoryRows(array $historyLogs, bool $includeNotes, string $scheduleMode = 'contract'): array
    {
        $isPlatform = ($scheduleMode === 'platform');
        $startHeader = $isPlatform ? 'Platform Period Start' : 'Period Start Date';
        $endHeader = $isPlatform ? 'Platform Period End' : 'Period End Date';

        $headers = [
            'Client',
            'Project',
            'Batch Name',
            'Action Type',
            $startHeader,
            $endHeader,
            'Licence Count',
            'Given By',
            'Logged By',
            'Logged Date',
        ];
        if ($includeNotes) {
            $headers[] = $isPlatform ? 'Platform Notes' : 'Renewal Notes / PO Reference';
        }

        $rows = [$headers];

        foreach ($historyLogs as $h) {
            if ($isPlatform) {
                $start = !empty($h['platform_period_start']) ? $h['platform_period_start'] : (!empty($h['effective_period_start']) ? $h['effective_period_start'] : ($h['period_start'] ?? null));
                $end = !empty($h['platform_period_end']) ? $h['platform_period_end'] : (!empty($h['effective_period_end']) ? $h['effective_period_end'] : ($h['period_end'] ?? null));
            } else {
                $start = $h['period_start'] ?? null;
                $end = $h['period_end'] ?? null;
            }

            $row = [
                $h['client_name'] ?? '-',
                $h['project_name'] ?? '-',
                $h['batch_name'] ?? '-',
                ucfirst($h['action_type'] ?? 'renewed'),
                !empty($start) ? date('d-m-Y', strtotime($start)) : '-',
                !empty($end) ? date('d-m-Y', strtotime($end)) : '-',
                (int) ($h['licence_count'] ?? 0),
                $h['given_by'] ?? '-',
                $h['creator_name'] ?? 'Admin',
                !empty($h['created_at']) ? date('d-m-Y h:i A', strtotime($h['created_at'])) : '-',
            ];
            if ($includeNotes) {
                $row[] = $h['notes'] ?? '-';
            }
            $rows[] = $row;
        }

        return $rows;
    }

    private static function workbookFiles(array $sheets): array
    {
        $files = [];
        $files['[Content_Types].xml'] = self::contentTypesXml($sheets);
        $files['_rels/.rels'] = self::rootRelsXml();
        $files['xl/workbook.xml'] = self::workbookXml($sheets);
        $files['xl/_rels/workbook.xml.rels'] = self::workbookRelsXml($sheets);
        $files['xl/styles.xml'] = self::stylesXml();

        foreach ($sheets as $index => $sheet) {
            $sheetNum = $index + 1;
            $files["xl/worksheets/sheet{$sheetNum}.xml"] = self::worksheetXml(
                $sheet['rows'],
                $sheet['boldRows'] ?? [1],
                $sheet['numericColumns'] ?? []
            );
        }

        return $files;
    }

    private static function worksheetXml(array $rows, array $boldRows, array $numericColumns): string
    {
        $sheetData = '';
        $maxCols = 1;

        foreach ($rows as $rowIndex => $row) {
            $rowNum = $rowIndex + 1;
            $isBold = in_array($rowNum, $boldRows, true);
            $maxCols = max($maxCols, count($row));

            $sheetData .= "<row r=\"{$rowNum}\">";
            foreach ($row as $colIndex => $value) {
                $colLetter = self::columnLetter($colIndex);
                $cellRef = "{$colLetter}{$rowNum}";
                $isNumeric = is_numeric($value) && in_array($colLetter, $numericColumns, true);

                if ($isNumeric) {
                    $style = $isBold ? ' s="3"' : ' s="2"';
                    $valStr = (string) $value;
                    $sheetData .= "<c r=\"{$cellRef}\"{$style}><v>{$valStr}</v></c>";
                } else {
                    $style = $isBold ? ' s="1"' : ' s="0"';
                    $escaped = htmlspecialchars((string) ($value ?? ''), ENT_XML1 | ENT_QUOTES, 'UTF-8');
                    $sheetData .= "<c r=\"{$cellRef}\" t=\"inlineStr\"{$style}><is><t>{$escaped}</t></is></c>";
                }
            }
            $sheetData .= '</row>';
        }

        $colsXml = '<cols>';
        for ($c = 1; $c <= max(12, $maxCols); $c++) {
            $width = ($c === 1) ? '28' : (($c === 2 || $c === 3) ? '24' : '20');
            $colsXml .= "<col min=\"{$c}\" max=\"{$c}\" width=\"{$width}\" customWidth=\"1\"/>";
        }
        $colsXml .= '</cols>';

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            . $colsXml
            . '<sheetData>' . $sheetData . '</sheetData>'
            . '</worksheet>';
    }

    private static function stylesXml(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            . '<fonts count="2">'
            . '<font><sz val="11"/><color rgb="FF1E293B"/><name val="Calibri"/></font>'
            . '<font><b/><sz val="11"/><color rgb="FF0F172A"/><name val="Calibri"/></font>'
            . '</fonts>'
            . '<fills count="3">'
            . '<fill><patternFill patternType="none"/></fill>'
            . '<fill><patternFill patternType="gray125"/></fill>'
            . '<fill><patternFill patternType="solid"><fgColor rgb="FFF1F5F9"/></patternFill></fill>'
            . '</fills>'
            . '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>'
            . '<cellXfs count="4">'
            . '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
            . '<xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/>'
            . '<xf numFmtId="1" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>'
            . '<xf numFmtId="1" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyNumberFormat="1"/>'
            . '</cellXfs>'
            . '</styleSheet>';
    }

    private static function contentTypesXml(array $sheets): string
    {
        $overrides = '';
        foreach ($sheets as $index => $sheet) {
            $sheetNum = $index + 1;
            $overrides .= "<Override PartName=\"/xl/worksheets/sheet{$sheetNum}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>";
        }

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            . '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            . '<Default Extension="xml" ContentType="application/xml"/>'
            . '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
            . '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
            . $overrides
            . '</Types>';
    }

    private static function rootRelsXml(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            . '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
            . '</Relationships>';
    }

    private static function workbookXml(array $sheets): string
    {
        $sheetsXml = '';
        foreach ($sheets as $index => $sheet) {
            $sheetId = $index + 1;
            $rId = "rId{$sheetId}";
            $name = htmlspecialchars($sheet['name'], ENT_XML1 | ENT_QUOTES, 'UTF-8');
            $sheetsXml .= "<sheet name=\"{$name}\" sheetId=\"{$sheetId}\" r:id=\"{$rId}\"/>";
        }

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
            . '<sheets>' . $sheetsXml . '</sheets>'
            . '</workbook>';
    }

    private static function workbookRelsXml(array $sheets): string
    {
        $rels = '';
        foreach ($sheets as $index => $sheet) {
            $sheetNum = $index + 1;
            $rels .= "<Relationship Id=\"rId{$sheetNum}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet{$sheetNum}.xml\"/>";
        }
        $stylesRId = 'rId' . (count($sheets) + 1);
        $rels .= "<Relationship Id=\"{$stylesRId}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>";

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            . $rels
            . '</Relationships>';
    }

    private static function columnLetter(int $index): string
    {
        $letter = '';
        while ($index >= 0) {
            $letter = chr(($index % 26) + 65) . $letter;
            $index = intdiv($index, 26) - 1;
        }
        return $letter;
    }

    private static function zip(array $files): string
    {
        $local = '';
        $central = '';
        $offset = 0;
        [$time, $date] = self::dosDateTime();

        foreach ($files as $name => $data) {
            $size = strlen($data);
            $crc = crc32($data);
            if ($crc < 0) {
                $crc += 4294967296;
            }

            $header = pack('VvvvvvVVVvv', 0x04034b50, 20, 0, 0, $time, $date, $crc, $size, $size, strlen($name), 0) . $name;
            $central .= pack('VvvvvvvVVVvvvvvVV', 0x02014b50, 20, 20, 0, 0, $time, $date, $crc, $size, $size, strlen($name), 0, 0, 0, 0, 0, $offset) . $name;
            $local .= $header . $data;
            $offset += strlen($header) + $size;
        }

        return $local . $central . pack('VvvvvVVv', 0x06054b50, 0, 0, count($files), count($files), strlen($central), strlen($local), 0);
    }

    private static function dosDateTime(): array
    {
        $now = getdate();
        return [
            ($now['hours'] << 11) | ($now['minutes'] << 5) | (int) floor($now['seconds'] / 2),
            (($now['year'] - 1980) << 9) | ($now['mon'] << 5) | $now['mday'],
        ];
    }
}
